name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Print the machine's IP address
        ip -4 addr show scope global | grep inet | awk '{print "Machine IP:", $2}'

        # Allow connections to port 5000
        sudo ufw allow 5000

        # Add your test commands here, if applicable

    - name: Deploy Flask app
      run: |
        python API.py  # Replace with the actual script name

