name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install streamlit

    - name: Set environment variable
      run: |
        echo "REPLICATE_API_TOKEN=01c6df94ecaf955997fd6cb0ad0ab00eead53f47" >> $GITHUB_ENV

    - name: Run Streamlit app
      run: streamlit run st.py  # Replace with your actual app file name

    # Add more steps as needed for your deployment process, such as deploying to a hosting service.
